import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from '@/app/(components)/root/NavigationBar/SideBar'
import structureClasses from '@/lib/Shared/structureClasses'
import { useColorModeValue } from '@/lib/Shared/ColorModeHandler'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={structureClasses(useColorModeValue('', `dark`), '')}>
      <body className={inter.className}>
        <SideBar />

        <div className={structureClasses('px-2 pt-2 text-gray-700 dark:text-gray-200 lg:ml-72')}>{children}</div>
      </body>
    </html>
  )
}
