import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from '@/app/(components)/root/NavigationBar/SideBar'
import structureClasses from '@/lib/Shared/structureClasses'
import { useColorModeValue } from '@/lib/Shared/ColorModeHandler'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const ColorSettings = {
  lightBackground: 'bg-neutral-100',
  raw_darkBackground: 'bg-neutral-800',
  darkBackground: 'dark:bg-neutral-800',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { lightBackground, darkBackground, raw_darkBackground } = ColorSettings

  return (
    <html lang='en' className={structureClasses(useColorModeValue(lightBackground, `dark ${raw_darkBackground}`), '')}>
      <body className={inter.className}>
        <SideBar />

        <div className={structureClasses('px-4 pt-4 text-gray-700 dark:text-gray-200 lg:ml-72', lightBackground, darkBackground)}>{children}</div>
      </body>
    </html>
  )
}
